#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.subset({"kind": "Deployment"}),expects="1+"
---
spec:
  template:
    spec:
      #@overlay/match missing_ok=True
      nodeSelector:
        #@overlay/match missing_ok=True
        custom.tkg/node-type: infra
      #@overlay/match missing_ok=True
      tolerations:
        #@overlay/append
        - key: custom.tkg/node-type
          value: infra
          operator: Equal
          effect: NoSchedule